GEN_MODE: ddpm
MODEL_NAME: csicogen_lite
DIFF_TIMESTEPS: 100
DIFF_PRED_MODE: x0
CODEBOOK_SIZE: 256
DIFF_MODEL_DIM: 48
DIFF_MODEL_BLOCKS: 3
DIFF_MODEL_ATTN_EVERY: 3
DIFF_INFER_STEPS: 0
DIFF_INFER_FEEDBACK_STEPS: 100
DIFF_INFER_SAMPLER: ddpm
DIFF_DDIM_ETA: 0.0
SAMPLE_PRINT_EVERY_STEP: false
DIFF_STEP_METRIC_TIMESTEPS: none
